### PR TITLE
MH-12607 fast-composer-operations: Lossless Concat

### PR DESCRIPTION
**Pull request by phoebem**
Hi Lars,

Thanks for all the hard work you put into cleaning up the three versions of process.
I pulled all the concat changes into this pr against your branch, hopefully, this pr is more manageable.
Then we only have to deal with process-smil for the next release.

Phoebe.

### CODE REVIEW

**Comment by lkiesow** [comment]
Reviewing this right now.
Will create an updated pr against opencast once I'm done if I don't find anything major.
If you want live updates I'm still in IRC for a while ;-)
Let's see if we can get this in before the feature freeze.

**Comment by phoebem** [comment]
Thanks so much for working on getting this in.
I just joined the forum for the first time.
Let me know if you need anything else from me on these features.

By the way, after the feature freeze, when you get a chance, let’s touch base on process-smil.

Phoebe.

**Comment by lkiesow** [comment]
I meant the IRC channel on Freenode: #opencast.
https://webchat.freenode.net/?channels=opencast

**Comment by lkiesow** [comment]
Ah, I see you have been there earlier as well

**Comment by lkiesow** [comment]
Using [`-safe 0`](https://www.ffmpeg.org/ffmpeg-formats.html#Options) sounds unsafe. Is there a particular reason for using it?

**Comment by phoebem** [comment]
It is required for absolute paths.

Phoebe.

**Pull request merged**
